spring:
  application:
    name: landingpage
  datasource:
    #192.168.124.3:3316
    url: jdbc:mysql://192.168.124.3:3316/jinguizi?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&&serverTimezone=Hongkong
    #url: jdbc:mysql://localhost:3306/jinguizi?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&&serverTimezone=Hongkong
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 200MB
#  redis:
#    host: 192.168.200.128
#    port: 6379
#    database: 0
#    jedis:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 10
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms
#        # 连接池中最小空闲连接
#        min-idle: 0
#        # 连接池中的最大空闲连接
#        max-idle: 8
#    # 连接超时时间毫秒
#    timeout: 5000ms

server:
  port: 12121
mybatis:
  typeAliasesPackage: com.jinguizi
  mapperLocations: classpath:mapper/*.xml
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

filepath: D://image
host: https://xxx.xxx.com